### ISSUE TITLE
Sets Keyboard to Off (Effectively)

### ISSUE THREAD

**Issue by Ruscios** [bambash/sys76-kb#7]
https://github.com/bambash/sys76-kb/blob/639bc197f99925a96a6fd37dd22964e6e2276056/pkg/keyboard.go#L25

This line sets the keyboard on the Oryx Pro 6 (Oryp6) to off, as white is (255, 255, 255). I have a hunch that this might be the case with other models as well.

**Comment by Ruscios** [comment]
#8 Should fix this

**Comment by bambash** [comment]
Merged, cheers!
